//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PublisherCerts2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_4170_ncmaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_4170_ncmaEntities object using the connection string found in the 'DB_4170_ncmaEntities' section of the application configuration file.
        /// </summary>
        public DB_4170_ncmaEntities() : base("name=DB_4170_ncmaEntities", "DB_4170_ncmaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_4170_ncmaEntities object.
        /// </summary>
        public DB_4170_ncmaEntities(string connectionString) : base(connectionString, "DB_4170_ncmaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_4170_ncmaEntities object.
        /// </summary>
        public DB_4170_ncmaEntities(EntityConnection connection) : base(connection, "DB_4170_ncmaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cert> certs
        {
            get
            {
                if ((_certs == null))
                {
                    _certs = base.CreateObjectSet<cert>("certs");
                }
                return _certs;
            }
        }
        private ObjectSet<cert> _certs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<certtype> certtypes
        {
            get
            {
                if ((_certtypes == null))
                {
                    _certtypes = base.CreateObjectSet<certtype>("certtypes");
                }
                return _certtypes;
            }
        }
        private ObjectSet<certtype> _certtypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<country> countries
        {
            get
            {
                if ((_countries == null))
                {
                    _countries = base.CreateObjectSet<country>("countries");
                }
                return _countries;
            }
        }
        private ObjectSet<country> _countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dojo> dojoes
        {
            get
            {
                if ((_dojoes == null))
                {
                    _dojoes = base.CreateObjectSet<dojo>("dojoes");
                }
                return _dojoes;
            }
        }
        private ObjectSet<dojo> _dojoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dojoinstructor> dojoinstructors
        {
            get
            {
                if ((_dojoinstructors == null))
                {
                    _dojoinstructors = base.CreateObjectSet<dojoinstructor>("dojoinstructors");
                }
                return _dojoinstructors;
            }
        }
        private ObjectSet<dojoinstructor> _dojoinstructors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<instructortype> instructortypes
        {
            get
            {
                if ((_instructortypes == null))
                {
                    _instructortypes = base.CreateObjectSet<instructortype>("instructortypes");
                }
                return _instructortypes;
            }
        }
        private ObjectSet<instructortype> _instructortypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<member> members
        {
            get
            {
                if ((_members == null))
                {
                    _members = base.CreateObjectSet<member>("members");
                }
                return _members;
            }
        }
        private ObjectSet<member> _members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<membercert> membercerts
        {
            get
            {
                if ((_membercerts == null))
                {
                    _membercerts = base.CreateObjectSet<membercert>("membercerts");
                }
                return _membercerts;
            }
        }
        private ObjectSet<membercert> _membercerts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rank> ranks
        {
            get
            {
                if ((_ranks == null))
                {
                    _ranks = base.CreateObjectSet<rank>("ranks");
                }
                return _ranks;
            }
        }
        private ObjectSet<rank> _ranks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tournament> tournaments
        {
            get
            {
                if ((_tournaments == null))
                {
                    _tournaments = base.CreateObjectSet<tournament>("tournaments");
                }
                return _tournaments;
            }
        }
        private ObjectSet<tournament> _tournaments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwCertificate> vwCertificates
        {
            get
            {
                if ((_vwCertificates == null))
                {
                    _vwCertificates = base.CreateObjectSet<vwCertificate>("vwCertificates");
                }
                return _vwCertificates;
            }
        }
        private ObjectSet<vwCertificate> _vwCertificates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the certs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocerts(cert cert)
        {
            base.AddObject("certs", cert);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the certtypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocerttypes(certtype certtype)
        {
            base.AddObject("certtypes", certtype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocountries(country country)
        {
            base.AddObject("countries", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dojoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodojoes(dojo dojo)
        {
            base.AddObject("dojoes", dojo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dojoinstructors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodojoinstructors(dojoinstructor dojoinstructor)
        {
            base.AddObject("dojoinstructors", dojoinstructor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the instructortypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToinstructortypes(instructortype instructortype)
        {
            base.AddObject("instructortypes", instructortype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomembers(member member)
        {
            base.AddObject("members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the membercerts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomembercerts(membercert membercert)
        {
            base.AddObject("membercerts", membercert);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ranks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToranks(rank rank)
        {
            base.AddObject("ranks", rank);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tournaments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotournaments(tournament tournament)
        {
            base.AddObject("tournaments", tournament);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwCertificates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwCertificates(vwCertificate vwCertificate)
        {
            base.AddObject("vwCertificates", vwCertificate);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="cert")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cert : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cert object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static cert Createcert(global::System.Int32 id)
        {
            cert cert = new cert();
            cert.ID = id;
            return cert;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MemberID;
        partial void OnMemberIDChanging(Nullable<global::System.Int32> value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstructorID
        {
            get
            {
                return _InstructorID;
            }
            set
            {
                OnInstructorIDChanging(value);
                ReportPropertyChanging("InstructorID");
                _InstructorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstructorID");
                OnInstructorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InstructorID;
        partial void OnInstructorIDChanging(Nullable<global::System.Int32> value);
        partial void OnInstructorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CertTypeID
        {
            get
            {
                return _CertTypeID;
            }
            set
            {
                OnCertTypeIDChanging(value);
                ReportPropertyChanging("CertTypeID");
                _CertTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CertTypeID");
                OnCertTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CertTypeID;
        partial void OnCertTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnCertTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Completed;
        partial void OnCompletedChanging(Nullable<global::System.Boolean> value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemberActivityID
        {
            get
            {
                return _MemberActivityID;
            }
            set
            {
                OnMemberActivityIDChanging(value);
                ReportPropertyChanging("MemberActivityID");
                _MemberActivityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberActivityID");
                OnMemberActivityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MemberActivityID;
        partial void OnMemberActivityIDChanging(Nullable<global::System.Int32> value);
        partial void OnMemberActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CertDate
        {
            get
            {
                return _CertDate;
            }
            set
            {
                OnCertDateChanging(value);
                ReportPropertyChanging("CertDate");
                _CertDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CertDate");
                OnCertDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CertDate;
        partial void OnCertDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCertDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TourneyID
        {
            get
            {
                return _TourneyID;
            }
            set
            {
                OnTourneyIDChanging(value);
                ReportPropertyChanging("TourneyID");
                _TourneyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TourneyID");
                OnTourneyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TourneyID;
        partial void OnTourneyIDChanging(Nullable<global::System.Int32> value);
        partial void OnTourneyIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="certtype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class certtype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new certtype object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static certtype Createcerttype(global::System.Int32 id)
        {
            certtype certtype = new certtype();
            certtype.ID = id;
            return certtype;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ValidationDurationInDays
        {
            get
            {
                return _ValidationDurationInDays;
            }
            set
            {
                OnValidationDurationInDaysChanging(value);
                ReportPropertyChanging("ValidationDurationInDays");
                _ValidationDurationInDays = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ValidationDurationInDays");
                OnValidationDurationInDaysChanged();
            }
        }
        private Nullable<global::System.Int32> _ValidationDurationInDays;
        partial void OnValidationDurationInDaysChanging(Nullable<global::System.Int32> value);
        partial void OnValidationDurationInDaysChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new country object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static country Createcountry(global::System.Int32 id)
        {
            country country = new country();
            country.ID = id;
            return country;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="dojo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dojo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dojo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static dojo Createdojo(global::System.Int32 id)
        {
            dojo dojo = new dojo();
            dojo.ID = id;
            return dojo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Style
        {
            get
            {
                return _Style;
            }
            set
            {
                OnStyleChanging(value);
                ReportPropertyChanging("Style");
                _Style = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Style");
                OnStyleChanged();
            }
        }
        private global::System.String _Style;
        partial void OnStyleChanging(global::System.String value);
        partial void OnStyleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="dojoinstructor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dojoinstructor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dojoinstructor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dojoID">Initial value of the DojoID property.</param>
        public static dojoinstructor Createdojoinstructor(global::System.Int32 id, global::System.Int32 dojoID)
        {
            dojoinstructor dojoinstructor = new dojoinstructor();
            dojoinstructor.ID = id;
            dojoinstructor.DojoID = dojoID;
            return dojoinstructor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DojoID
        {
            get
            {
                return _DojoID;
            }
            set
            {
                if (_DojoID != value)
                {
                    OnDojoIDChanging(value);
                    ReportPropertyChanging("DojoID");
                    _DojoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DojoID");
                    OnDojoIDChanged();
                }
            }
        }
        private global::System.Int32 _DojoID;
        partial void OnDojoIDChanging(global::System.Int32 value);
        partial void OnDojoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstructorID
        {
            get
            {
                return _InstructorID;
            }
            set
            {
                OnInstructorIDChanging(value);
                ReportPropertyChanging("InstructorID");
                _InstructorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstructorID");
                OnInstructorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InstructorID;
        partial void OnInstructorIDChanging(Nullable<global::System.Int32> value);
        partial void OnInstructorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstructorTypeID
        {
            get
            {
                return _InstructorTypeID;
            }
            set
            {
                OnInstructorTypeIDChanging(value);
                ReportPropertyChanging("InstructorTypeID");
                _InstructorTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstructorTypeID");
                OnInstructorTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InstructorTypeID;
        partial void OnInstructorTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnInstructorTypeIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="instructortype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class instructortype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new instructortype object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static instructortype Createinstructortype(global::System.Int32 id)
        {
            instructortype instructortype = new instructortype();
            instructortype.ID = id;
            return instructortype;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstructorTypeName
        {
            get
            {
                return _InstructorTypeName;
            }
            set
            {
                OnInstructorTypeNameChanging(value);
                ReportPropertyChanging("InstructorTypeName");
                _InstructorTypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstructorTypeName");
                OnInstructorTypeNameChanged();
            }
        }
        private global::System.String _InstructorTypeName;
        partial void OnInstructorTypeNameChanging(global::System.String value);
        partial void OnInstructorTypeNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new member object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static member Createmember(global::System.Int32 id, global::System.Int32 active)
        {
            member member = new member();
            member.ID = id;
            member.Active = active;
            return member;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                OnSuffixChanging(value);
                ReportPropertyChanging("Suffix");
                _Suffix = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suffix");
                OnSuffixChanged();
            }
        }
        private global::System.String _Suffix;
        partial void OnSuffixChanging(global::System.String value);
        partial void OnSuffixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                OnStateIDChanging(value);
                ReportPropertyChanging("StateID");
                _StateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateID");
                OnStateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StateID;
        partial void OnStateIDChanging(Nullable<global::System.Int32> value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CountryID
        {
            get
            {
                return _CountryID;
            }
            set
            {
                OnCountryIDChanging(value);
                ReportPropertyChanging("CountryID");
                _CountryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryID");
                OnCountryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CountryID;
        partial void OnCountryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCountryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private global::System.String _HomePhone;
        partial void OnHomePhoneChanging(global::System.String value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private global::System.String _CellPhone;
        partial void OnCellPhoneChanging(global::System.String value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PlanID
        {
            get
            {
                return _PlanID;
            }
            set
            {
                OnPlanIDChanging(value);
                ReportPropertyChanging("PlanID");
                _PlanID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlanID");
                OnPlanIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PlanID;
        partial void OnPlanIDChanging(Nullable<global::System.Int32> value);
        partial void OnPlanIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DojoID
        {
            get
            {
                return _DojoID;
            }
            set
            {
                OnDojoIDChanging(value);
                ReportPropertyChanging("DojoID");
                _DojoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DojoID");
                OnDojoIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DojoID;
        partial void OnDojoIDChanging(Nullable<global::System.Int32> value);
        partial void OnDojoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemberTypeID
        {
            get
            {
                return _MemberTypeID;
            }
            set
            {
                OnMemberTypeIDChanging(value);
                ReportPropertyChanging("MemberTypeID");
                _MemberTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberTypeID");
                OnMemberTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MemberTypeID;
        partial void OnMemberTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnMemberTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateJoined
        {
            get
            {
                return _DateJoined;
            }
            set
            {
                OnDateJoinedChanging(value);
                ReportPropertyChanging("DateJoined");
                _DateJoined = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateJoined");
                OnDateJoinedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateJoined;
        partial void OnDateJoinedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateJoinedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfRank
        {
            get
            {
                return _DateOfRank;
            }
            set
            {
                OnDateOfRankChanging(value);
                ReportPropertyChanging("DateOfRank");
                _DateOfRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfRank");
                OnDateOfRankChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfRank;
        partial void OnDateOfRankChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfRankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RankID
        {
            get
            {
                return _RankID;
            }
            set
            {
                OnRankIDChanging(value);
                ReportPropertyChanging("RankID");
                _RankID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RankID");
                OnRankIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RankID;
        partial void OnRankIDChanging(Nullable<global::System.Int32> value);
        partial void OnRankIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Active
        {
            get
            {
                return _Active;
            }
            set
            {
                if (_Active != value)
                {
                    OnActiveChanging(value);
                    ReportPropertyChanging("Active");
                    _Active = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Active");
                    OnActiveChanged();
                }
            }
        }
        private global::System.Int32 _Active;
        partial void OnActiveChanging(global::System.Int32 value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateInactive
        {
            get
            {
                return _DateInactive;
            }
            set
            {
                OnDateInactiveChanging(value);
                ReportPropertyChanging("DateInactive");
                _DateInactive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateInactive");
                OnDateInactiveChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateInactive;
        partial void OnDateInactiveChanging(Nullable<global::System.DateTime> value);
        partial void OnDateInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateLastPaid
        {
            get
            {
                return _DateLastPaid;
            }
            set
            {
                OnDateLastPaidChanging(value);
                ReportPropertyChanging("DateLastPaid");
                _DateLastPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLastPaid");
                OnDateLastPaidChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateLastPaid;
        partial void OnDateLastPaidChanging(Nullable<global::System.DateTime> value);
        partial void OnDateLastPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="membercert")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class membercert : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new membercert object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static membercert Createmembercert(global::System.Int32 id)
        {
            membercert membercert = new membercert();
            membercert.ID = id;
            return membercert;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MemberID;
        partial void OnMemberIDChanging(Nullable<global::System.Int32> value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DojoID
        {
            get
            {
                return _DojoID;
            }
            set
            {
                OnDojoIDChanging(value);
                ReportPropertyChanging("DojoID");
                _DojoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DojoID");
                OnDojoIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DojoID;
        partial void OnDojoIDChanging(Nullable<global::System.Int32> value);
        partial void OnDojoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CertificateTypeID
        {
            get
            {
                return _CertificateTypeID;
            }
            set
            {
                OnCertificateTypeIDChanging(value);
                ReportPropertyChanging("CertificateTypeID");
                _CertificateTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CertificateTypeID");
                OnCertificateTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CertificateTypeID;
        partial void OnCertificateTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnCertificateTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RankText
        {
            get
            {
                return _RankText;
            }
            set
            {
                OnRankTextChanging(value);
                ReportPropertyChanging("RankText");
                _RankText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RankText");
                OnRankTextChanged();
            }
        }
        private global::System.String _RankText;
        partial void OnRankTextChanging(global::System.String value);
        partial void OnRankTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstructorID
        {
            get
            {
                return _InstructorID;
            }
            set
            {
                OnInstructorIDChanging(value);
                ReportPropertyChanging("InstructorID");
                _InstructorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstructorID");
                OnInstructorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InstructorID;
        partial void OnInstructorIDChanging(Nullable<global::System.Int32> value);
        partial void OnInstructorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstructorTypeID
        {
            get
            {
                return _InstructorTypeID;
            }
            set
            {
                OnInstructorTypeIDChanging(value);
                ReportPropertyChanging("InstructorTypeID");
                _InstructorTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstructorTypeID");
                OnInstructorTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _InstructorTypeID;
        partial void OnInstructorTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnInstructorTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FromDate
        {
            get
            {
                return _FromDate;
            }
            set
            {
                OnFromDateChanging(value);
                ReportPropertyChanging("FromDate");
                _FromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromDate");
                OnFromDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FromDate;
        partial void OnFromDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThruDate
        {
            get
            {
                return _ThruDate;
            }
            set
            {
                OnThruDateChanging(value);
                ReportPropertyChanging("ThruDate");
                _ThruDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThruDate");
                OnThruDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThruDate;
        partial void OnThruDateChanging(Nullable<global::System.DateTime> value);
        partial void OnThruDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Completed;
        partial void OnCompletedChanging(Nullable<global::System.Boolean> value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TourneyID
        {
            get
            {
                return _TourneyID;
            }
            set
            {
                OnTourneyIDChanging(value);
                ReportPropertyChanging("TourneyID");
                _TourneyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TourneyID");
                OnTourneyIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TourneyID;
        partial void OnTourneyIDChanging(Nullable<global::System.Int32> value);
        partial void OnTourneyIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="rank")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rank : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rank object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static rank Createrank(global::System.Int32 id)
        {
            rank rank = new rank();
            rank.ID = id;
            return rank;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="tournament")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tournament : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tournament object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tournament Createtournament(global::System.Int32 id)
        {
            tournament tournament = new tournament();
            tournament.ID = id;
            return tournament;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address3
        {
            get
            {
                return _Address3;
            }
            set
            {
                OnAddress3Changing(value);
                ReportPropertyChanging("Address3");
                _Address3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address3");
                OnAddress3Changed();
            }
        }
        private global::System.String _Address3;
        partial void OnAddress3Changing(global::System.String value);
        partial void OnAddress3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StateID
        {
            get
            {
                return _StateID;
            }
            set
            {
                OnStateIDChanging(value);
                ReportPropertyChanging("StateID");
                _StateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StateID");
                OnStateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StateID;
        partial void OnStateIDChanging(Nullable<global::System.Int32> value);
        partial void OnStateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TournDate
        {
            get
            {
                return _TournDate;
            }
            set
            {
                OnTournDateChanging(value);
                ReportPropertyChanging("TournDate");
                _TournDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TournDate");
                OnTournDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TournDate;
        partial void OnTournDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTournDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_4170_ncmaModel", Name="vwCertificate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwCertificate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwCertificate object.
        /// </summary>
        /// <param name="fullName">Initial value of the FullName property.</param>
        /// <param name="instructorsName">Initial value of the InstructorsName property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static vwCertificate CreatevwCertificate(global::System.String fullName, global::System.String instructorsName, global::System.Int32 id)
        {
            vwCertificate vwCertificate = new vwCertificate();
            vwCertificate.FullName = fullName;
            vwCertificate.InstructorsName = instructorsName;
            vwCertificate.ID = id;
            return vwCertificate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                if (_FullName != value)
                {
                    OnFullNameChanging(value);
                    ReportPropertyChanging("FullName");
                    _FullName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FullName");
                    OnFullNameChanged();
                }
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InstructorsName
        {
            get
            {
                return _InstructorsName;
            }
            set
            {
                if (_InstructorsName != value)
                {
                    OnInstructorsNameChanging(value);
                    ReportPropertyChanging("InstructorsName");
                    _InstructorsName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InstructorsName");
                    OnInstructorsNameChanged();
                }
            }
        }
        private global::System.String _InstructorsName;
        partial void OnInstructorsNameChanging(global::System.String value);
        partial void OnInstructorsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dojo
        {
            get
            {
                return _Dojo;
            }
            set
            {
                OnDojoChanging(value);
                ReportPropertyChanging("Dojo");
                _Dojo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dojo");
                OnDojoChanged();
            }
        }
        private global::System.String _Dojo;
        partial void OnDojoChanging(global::System.String value);
        partial void OnDojoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RankText
        {
            get
            {
                return _RankText;
            }
            set
            {
                OnRankTextChanging(value);
                ReportPropertyChanging("RankText");
                _RankText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RankText");
                OnRankTextChanged();
            }
        }
        private global::System.String _RankText;
        partial void OnRankTextChanging(global::System.String value);
        partial void OnRankTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InstructorType
        {
            get
            {
                return _InstructorType;
            }
            set
            {
                OnInstructorTypeChanging(value);
                ReportPropertyChanging("InstructorType");
                _InstructorType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InstructorType");
                OnInstructorTypeChanged();
            }
        }
        private global::System.String _InstructorType;
        partial void OnInstructorTypeChanging(global::System.String value);
        partial void OnInstructorTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CertType
        {
            get
            {
                return _CertType;
            }
            set
            {
                OnCertTypeChanging(value);
                ReportPropertyChanging("CertType");
                _CertType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CertType");
                OnCertTypeChanged();
            }
        }
        private global::System.String _CertType;
        partial void OnCertTypeChanging(global::System.String value);
        partial void OnCertTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TournamentDate
        {
            get
            {
                return _TournamentDate;
            }
            set
            {
                OnTournamentDateChanging(value);
                ReportPropertyChanging("TournamentDate");
                _TournamentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TournamentDate");
                OnTournamentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TournamentDate;
        partial void OnTournamentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTournamentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FromDate
        {
            get
            {
                return _FromDate;
            }
            set
            {
                OnFromDateChanging(value);
                ReportPropertyChanging("FromDate");
                _FromDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromDate");
                OnFromDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FromDate;
        partial void OnFromDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFromDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ThruDate
        {
            get
            {
                return _ThruDate;
            }
            set
            {
                OnThruDateChanging(value);
                ReportPropertyChanging("ThruDate");
                _ThruDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ThruDate");
                OnThruDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ThruDate;
        partial void OnThruDateChanging(Nullable<global::System.DateTime> value);
        partial void OnThruDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Completed;
        partial void OnCompletedChanging(Nullable<global::System.Boolean> value);
        partial void OnCompletedChanged();

        #endregion
    
    }

    #endregion
    
}
