//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class cert
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> InstructorID { get; set; }
        public Nullable<int> CertTypeID { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> MemberActivityID { get; set; }
        public Nullable<System.DateTime> CertDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TourneyID { get; set; }
    }
}
