//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineitem
    {
        public int ID { get; set; }
        public int productid { get; set; }
        public int qty { get; set; }
        public int discount { get; set; }
        public int invoiceid { get; set; }
    }
}
