//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberactivity
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ActivityDescription { get; set; }
    }
}
