//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournresult
    {
        public int ID { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> TournAcheivementTypeID { get; set; }
        public Nullable<int> TournDivisionID { get; set; }
        public Nullable<int> TournCompTypeID { get; set; }
    }
}
