//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMemberGrid
    {
        public string Last { get; set; }
        public string First { get; set; }
        public string Country { get; set; }
        public string Dojo { get; set; }
        public string MemType { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<System.DateTime> DateOfRank { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> DateLastPaid { get; set; }
        public int ID { get; set; }
        public string RankText { get; set; }
    }
}
