//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTournResult
    {
        public Nullable<int> MemberID { get; set; }
        public int tournresultid { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> TournAcheivementTypeID { get; set; }
        public Nullable<int> TournDivisionID { get; set; }
        public Nullable<int> TournCompTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TournDate { get; set; }
        public string City { get; set; }
        public string FullName { get; set; }
        public string Last { get; set; }
        public string First { get; set; }
        public string Country { get; set; }
        public string Dojo { get; set; }
        public string MemType { get; set; }
        public string Rank { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<System.DateTime> DateOfRank { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> DateLastPaid { get; set; }
        public string tourncomptypename { get; set; }
        public string tournstate { get; set; }
        public string tournachievementtypename { get; set; }
        public string tournachievementtypedesc { get; set; }
        public string tourndivisionname { get; set; }
        public string tourndivisiondesc { get; set; }
        public string tourncomptypedesc { get; set; }
    }
}
